DELETE FROM T_TREIBER WHERE treiber_id = 297;
DELETE FROM T_KONDITION_DEF WHERE treiber_id = 297;
DELETE FROM T_PARA_DEF WHERE treiber_id = 297;
DELETE FROM T_VAR_DEF WHERE treiber_id = 297;
DELETE FROM T_ALARM_DEF WHERE treiber_id = 297;
DELETE FROM T_EVENT_DEF WHERE treiber_id = 297;
INSERT INTO T_TREIBER (treiber_id, treiber_name) VALUES (297, 'XY_Tisch');
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('TimeStamp', 297, 2, 1, 1001);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('Device', 297, 2, 2, 1002);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('Carrier', 297, 2, 3, 1003);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PosInCarrier', 297, 2, 4, 1004);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('X_Pos', 297, 2, 5, 1005);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('Y_Pos', 297, 2, 6, 1006);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('Strom', 297, 2, 7, 1007);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('Operator', 297, 2, 8, 1008);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('MessNr', 297, 2, 9, 1040);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('XY_Tisch_Data', 297, 1, 6001);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('XY_Tisch_Device_Finish', 297, 2, 6002);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (100000000, 297, 1, 'Undefined variable', 1);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (100000005, 297, 1, 'No report linked to event', 2);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (102000301, 297, 1, 'Source folder does not exist', 3);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (102000302, 297, 1, 'Unable to move file', 4);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (102000303, 297, 1, 'Unable to create folders', 5);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (102000304, 297, 1, 'Parse error', 6);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (102000305, 297, 1, 'PKS error', 7);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (102000921, 297, 1, 'IVL file has invalid format', 8);
