DELETE FROM T_TREIBER WHERE treiber_id = 335;
DELETE FROM T_KONDITION_DEF WHERE treiber_id = 335;
DELETE FROM T_PARA_DEF WHERE treiber_id = 335;
DELETE FROM T_VAR_DEF WHERE treiber_id = 335;
DELETE FROM T_ALARM_DEF WHERE treiber_id = 335;
DELETE FROM T_EVENT_DEF WHERE treiber_id = 335;
INSERT INTO T_TREIBER (treiber_id, treiber_name) VALUES (335, 'Xenon');
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('AlarmCode', 335, 2, 1, 0);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('AlarmID', 335, 2, 2, 1);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('AlarmsEnabled', 335, 2, 3, 2);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('AlarmsSet', 335, 2, 4, 3);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('AlarmText', 335, 2, 5, 4);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('AppSoftRev', 335, 2, 6, 5);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('Clock', 335, 2, 7, 6);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('CommunicationState', 335, 2, 8, 7);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ControlState', 335, 2, 9, 8);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('DeviceID', 335, 2, 10, 9);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10State', 335, 2, 11, 10);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('EnableSpooling', 335, 2, 12, 11);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('EqConstID', 335, 2, 13, 12);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('EqpModel', 335, 2, 14, 13);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('EqpName', 335, 2, 15, 14);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('EqpSerialNum', 335, 2, 16, 15);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('EstablishCommunicationsTimeout', 335, 2, 17, 16);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('EventsEnabled', 335, 2, 18, 17);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('GEMRev', 335, 2, 19, 18);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('Heartbeat', 335, 2, 20, 19);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('InitCommState', 335, 2, 21, 20);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('InitControlState', 335, 2, 22, 21);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('InitOnlineSubstate', 335, 2, 23, 22);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('LocationID', 335, 2, 24, 23);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('MaterialID', 335, 2, 25, 24);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('MaterialState', 335, 2, 26, 25);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('MaxSpoolTransmit', 335, 2, 27, 26);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('OfflineSubstate', 335, 2, 28, 27);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('OnlineFailState', 335, 2, 29, 28);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('OnlineSubstate', 335, 2, 30, 29);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('OperatorAction', 335, 2, 31, 30);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('OperatorCommand', 335, 2, 32, 31);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('OverWriteSpool', 335, 2, 33, 32);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PPChangeName', 335, 2, 34, 33);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PPChangeStatus', 335, 2, 35, 34);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PPError', 335, 2, 36, 35);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PPExecName', 335, 2, 37, 36);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PPFormat', 335, 2, 38, 37);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PPUsedName', 335, 2, 39, 38);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousControlState', 335, 2, 40, 39);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10State', 335, 2, 41, 40);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessState', 335, 2, 42, 41);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResults', 335, 2, 43, 42);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessState', 335, 2, 44, 43);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ReplyBitS10', 335, 2, 45, 44);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ReplyBitS5', 335, 2, 46, 45);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ReplyBitS6', 335, 2, 47, 46);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('SpoolCountActual', 335, 2, 48, 47);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('SpoolCountTotal', 335, 2, 49, 48);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('SpooledRptID', 335, 2, 50, 49);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('SpoolFullTime', 335, 2, 51, 50);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('SpoolLoadSubstate', 335, 2, 52, 51);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('SpoolStartTime', 335, 2, 53, 52);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('SpoolState', 335, 2, 54, 53);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('SpoolUnloadSubstate', 335, 2, 55, 54);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('TimeFormat', 335, 2, 56, 55);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('UseTimeSync', 335, 2, 57, 56);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_KappaID', 335, 2, 58, 1000);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M01FleeceLot', 335, 2, 59, 1001);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M11EqCheckSub', 335, 2, 60, 1002);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M11FleeceLot', 335, 2, 61, 1003);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M11Labeled', 335, 2, 62, 1004);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M11LabelLot', 335, 2, 63, 1005);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M11ModuleID', 335, 2, 64, 1006);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M11Recipe', 335, 2, 65, 1007);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M11State', 335, 2, 66, 1008);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M11SubID', 335, 2, 67, 1009);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M12Con1Lot', 335, 2, 68, 1010);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M12ModuleID', 335, 2, 69, 1011);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M12Recipe', 335, 2, 70, 1012);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M12State', 335, 2, 71, 1013);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M12SubID', 335, 2, 72, 1014);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M13Coil1ID', 335, 2, 73, 1015);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M13Coil2ID', 335, 2, 74, 1016);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M13ModuleID', 335, 2, 75, 1017);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M13Recipe', 335, 2, 76, 1018);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M13State', 335, 2, 77, 1019);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M13SubID', 335, 2, 78, 1020);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M13UsedCellIDs', 335, 2, 79, 1021);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M14Con2Lot', 335, 2, 80, 1022);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M14ModuleID', 335, 2, 81, 1023);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M14Recipe', 335, 2, 82, 1024);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M14State', 335, 2, 83, 1025);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M14SubID', 335, 2, 84, 1026);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M21MetRecipe', 335, 2, 85, 1027);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M21MetPosOk', 335, 2, 86, 1028);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M21ModuleID', 335, 2, 87, 1029);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M21Paste1Lot', 335, 2, 88, 1030);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M21Paste2Lot', 335, 2, 89, 1031);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M21SubID', 335, 2, 90, 1032);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M31ActualTmp', 335, 2, 91, 1033);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M31DryDur', 335, 2, 92, 1034);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M31DryRecipe', 335, 2, 93, 1035);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M31SubID', 335, 2, 94, 1036);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M32OutputWell', 335, 2, 95, 1037);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M32SubID', 335, 2, 96, 1038);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M33ErrorCat', 335, 2, 97, 1039);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M33ModuleCls', 335, 2, 98, 1040);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_M33SubID', 335, 2, 99, 1041);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('XE_ZappaID', 335, 2, 100, 1042);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateCutter', 335, 2, 101, 2000);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateZappa1', 335, 2, 102, 2001);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateZappa2', 335, 2, 103, 2002);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateZappa3', 335, 2, 104, 2003);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateZappa4', 335, 2, 105, 2004);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateKappa1', 335, 2, 106, 2005);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateKappa2', 335, 2, 107, 2006);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateFurnace', 335, 2, 108, 2007);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateFinalNIO', 335, 2, 109, 2008);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateFinalIO', 335, 2, 110, 2009);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('E10StateTransfer', 335, 2, 111, 2010);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateCutter', 335, 2, 112, 3000);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateZappa1', 335, 2, 113, 3001);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateZappa2', 335, 2, 114, 3002);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateZappa3', 335, 2, 115, 3003);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateZappa4', 335, 2, 116, 3004);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateKappa1', 335, 2, 117, 3005);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateKappa2', 335, 2, 118, 3006);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateFurnace', 335, 2, 119, 3007);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateFinalNIO', 335, 2, 120, 3008);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateFinalIO', 335, 2, 121, 3009);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousE10StateTransfer', 335, 2, 122, 3010);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateCutter', 335, 2, 123, 4000);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateZappa1', 335, 2, 124, 4001);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateZappa2', 335, 2, 125, 4002);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateZappa3', 335, 2, 126, 4003);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateZappa4', 335, 2, 127, 4004);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateKappa1', 335, 2, 128, 4005);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateKappa2', 335, 2, 129, 4006);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateFurnace', 335, 2, 130, 4007);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateFinalNIO', 335, 2, 131, 4008);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateFinalIO', 335, 2, 132, 4009);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('PreviousProcessStateTransfer', 335, 2, 133, 4010);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultCutter', 335, 2, 134, 5000);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultZappaLabeling', 335, 2, 135, 5001);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultZappaAdhesion1', 335, 2, 136, 5002);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultZappaCells', 335, 2, 137, 5003);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultZappaAdhesion2', 335, 2, 138, 5004);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultKappa', 335, 2, 139, 5005);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultFurnace', 335, 2, 140, 5006);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultFinalNIO', 335, 2, 141, 5007);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessingResultFinalIO', 335, 2, 142, 5008);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateCutter', 335, 2, 143, 6000);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateZappa1', 335, 2, 144, 6001);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateZappa2', 335, 2, 145, 6002);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateZappa3', 335, 2, 146, 6003);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateZappa4', 335, 2, 147, 6004);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateKappa1', 335, 2, 148, 6005);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateKappa2', 335, 2, 149, 6006);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateFurnace', 335, 2, 150, 6007);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateFinalNIO', 335, 2, 151, 6008);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateFinalIO', 335, 2, 152, 6009);
INSERT INTO T_VAR_DEF (var_name, treiber_id, var_typ, seq_nr, vid) VALUES ('ProcessStateTransfer', 335, 2, 153, 6010);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('AlarmDetected', 335, 1, 0);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('AlarmCleared', 335, 2, 1);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ControlStateLocal', 335, 3, 2);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ControlStateRemote', 335, 4, 3);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChange', 335, 5, 4);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('EquipmentOffline', 335, 6, 5);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('MaterialReceived', 335, 7, 6);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('MaterialRemoved', 335, 8, 7);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('MessageRecognition', 335, 9, 8);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('OperatorEquipmentConstantChange', 335, 10, 9);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompleted', 335, 11, 10);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStarted', 335, 12, 11);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChange', 335, 13, 12);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStopped', 335, 14, 13);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessProgramChange', 335, 15, 14);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessProgramCreate', 335, 16, 15);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessProgramDelete', 335, 17, 16);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessProgramRecipeSelected', 335, 18, 17);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('SpoolingActivated', 335, 19, 18);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('SpoolingDeactivated', 335, 20, 19);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('SpoolingTransmitFailure', 335, 21, 20);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeCutter', 335, 22, 1000);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeZappa1', 335, 23, 1001);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeZappa2', 335, 24, 1002);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeZappa3', 335, 25, 1003);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeZappa4', 335, 26, 1004);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeKappa1', 335, 27, 1005);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeKappa2', 335, 28, 1006);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeFurnace', 335, 29, 1007);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeFinalIO', 335, 30, 1008);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeFinalNIO', 335, 31, 1009);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('E10StateChangeTransfer', 335, 32, 1010);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedCutter', 335, 33, 2000);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedZappaLabeling', 335, 34, 2001);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedZappaAdhesion1', 335, 35, 2002);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedZappaCells', 335, 36, 2003);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedZappaAdhesion2', 335, 37, 2004);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedKappa', 335, 38, 2005);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedFurnace', 335, 39, 2007);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedFinalIO', 335, 40, 2008);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedFinalNIO', 335, 41, 2009);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingCompletedTransfer', 335, 42, 2010);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeCutter', 335, 43, 3000);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeZappa1', 335, 44, 3001);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeZappa2', 335, 45, 3002);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeZappa3', 335, 46, 3003);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeZappa4', 335, 47, 3004);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeKappa1', 335, 48, 3005);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeKappa2', 335, 49, 3006);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeFurnace', 335, 50, 3007);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeFinalIO', 335, 51, 3008);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeFinalNIO', 335, 52, 3009);
INSERT INTO T_EVENT_DEF (event_name, treiber_id, seq_nr, ceid) VALUES ('ProcessingStateChangeTransfer', 335, 53, 3010);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (0, 335, 1, 'St00 Türen verriegeln nicht (E1.4->1)', 1);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1, 335, 1, 'St00 Türen entriegeln nicht (E1.4->0)', 2);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (2, 335, 1, 'St00 Notaus wegen Über- oder Unterdruck am Hauptluftventil (E1.0->1)', 3);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (3, 335, 1, 'St00 Alles zurückgesetzt, Maschine ausräumen.', 4);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (4, 335, 1, 'St00 Notaus weil verriegelte Türen geöffnet wurden (E1.3->1)', 5);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5, 335, 1, 'St00 Profibus-Teilnehmer ausgefallen, siehe Diagnose-Seite.', 6);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (64, 335, 1, 'St.01 Tisch: Timeout Tisch', 7);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (65, 335, 1, 'St.01 Tisch: Sensorfehler E63.2/E63.3', 8);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (66, 335, 1, 'St.01 Tisch: Sensorfehler E63.0/E63.1', 9);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (68, 335, 1, 'St.01 Tisch: Schott nicht geöffnet (E63.0->0, E63.1->1)', 10);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (69, 335, 1, 'St.01 Tisch: Schott nicht geschlossen (E63.0->1, E63.1->0)', 11);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (70, 335, 1, 'St.01 Tisch: Vlies nicht geschnitten', 12);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (71, 335, 1, 'St.01 Tisch: fährt nicht aus (E63.2->1, E63.3->0)', 13);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (74, 335, 1, 'St.01 Tisch: fährt nicht ein (E63.2->0, E63.3->1)', 14);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (96, 335, 1, 'St.02 Zuschnitt: Messer fährt nicht in Grundstellung (E63.6->0, E63.7->1)', 15);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (97, 335, 1, 'St.02 Zuschnitt: Messer fährt nicht in Arbeitstellung (E63.6->1, E63.7->0)', 16);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (160, 335, 1, 'St.03 Vlieszuführung: Vlies Ende/Abriss während Transport', 17);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (161, 335, 1, 'St.03 Vlieszuführung: Timeout Transport', 18);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (162, 335, 1, 'St.03 Vlieszuführung: Fehler/Timeout Anlagekante', 19);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (163, 335, 1, 'St.03 Vlieszuführung: Fehler/Timeout Andruckrollen', 20);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (164, 335, 1, 'St.03 Vlieszuführung: Fehler/Timeout Kantensteuerung', 21);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (165, 335, 1, 'St.03 Vlieszuführung: Fehler Transportantrieb nicht bereit', 22);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (166, 335, 1, 'St.03 Vlieszuführung: Verkleidung offen', 23);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (168, 335, 1, 'St.03 Vlieszuführung: Rollenende erkannt', 24);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1000, 335, 1, 'St00 Türen verriegeln nicht (E1.4->1)', 25);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1001, 335, 1, 'St00 Türen entriegeln nicht (E1.4->0)', 26);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1002, 335, 1, 'St00 Notaus wegen Über- oder Unterdruck am Hauptluftventil (E1.0->1)', 27);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1003, 335, 1, 'St00 Alles zurückgesetzt, Maschine ausräumen.', 28);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1004, 335, 1, 'St00 Notaus weil verriegelte Türen geöffnet wurden (E1.3->1)', 29);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1005, 335, 1, 'St00 Profibus-Teilnehmer ausgefallen, siehe Diagnose-Seite.', 30);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1032, 335, 1, 'Notabschaltung durch Station 01', 31);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1033, 335, 1, 'Notabschaltung durch Station 02', 32);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1034, 335, 1, 'Notabschaltung durch Station 03', 33);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1035, 335, 1, 'Notabschaltung durch Station 04', 34);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1036, 335, 1, 'Notabschaltung durch Station 05', 35);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1037, 335, 1, 'Notabschaltung durch Station 06', 36);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1038, 335, 1, 'Notabschaltung durch Station 07', 37);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1064, 335, 1, 'St.01 Tisch: Antrieb nicht bereit', 38);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1065, 335, 1, 'St.01 Tisch: Antrieb meldet Fehler', 39);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1066, 335, 1, 'St.01 Tisch: Schott schließt nicht ', 40);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1067, 335, 1, 'St.01 Tisch: Schott öffnet nicht ', 41);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1068, 335, 1, 'St.01 Tisch: Vakuumadapter geht nicht hoch', 42);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1069, 335, 1, 'St.01 Tisch: Vakuumadapter geht nicht runter', 43);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1070, 335, 1, 'St.01 Tisch: Spannleiste hinten geht nicht hoch', 44);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1071, 335, 1, 'St.01 Tisch: Spannleiste hinten geht nicht runter', 45);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1072, 335, 1, 'St.01 Tisch: Spannleisten Seite 1 gehen nicht hoch', 46);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1073, 335, 1, 'St.01 Tisch: Spannleisten Seite 1 gehen nicht runter', 47);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1074, 335, 1, 'St.01 Tisch: Spannleisten Seite 2 gehen nicht hoch', 48);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1075, 335, 1, 'St.01 Tisch: Spannleisten Seite 2 gehen nicht runter', 49);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1096, 335, 1, 'St.02 Zellenvereinzelung 1: Antrieb für Kante nicht bereit', 50);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1097, 335, 1, 'St.02 Zellenvereinzelung 1: Antrieb für Kante meldet Fehler', 51);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1098, 335, 1, 'St.02 Zellenvereinzelung 1: Antrieb für Band nicht bereit', 52);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1099, 335, 1, 'St.02 Zellenvereinzelung 1: Antrieb für Band meldet Fehler', 53);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1102, 335, 1, 'St.02 Zellenvereinzelung 1: Antrieb_Kante hinten nicht auf "stumpf"', 54);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1103, 335, 1, 'St.02 Zellenvereinzelung 1: Antrieb_Kante hinten nicht auf "scharf"', 55);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1104, 335, 1, 'St.02 Zellenvereinzelung 1: Antrieb_Kante vorn nicht auf "stumpf"', 56);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1105, 335, 1, 'St.02 Zellenvereinzelung 1: Antrieb_Kante vorn nicht auf "scharf"', 57);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1106, 335, 1, 'St.02 Zellenvereinzelung 1: keine Freigabe für Schlitten von den Dreheinheiten', 58);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1107, 335, 1, 'St.02 Zellenvereinzelung 1: keine Zelle erkannt', 59);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1128, 335, 1, 'St.02 Abwickler 1: Antrieb nicht bereit', 60);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1129, 335, 1, 'St.02 Abwickler 1: Antrieb meldet Fehler', 61);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1130, 335, 1, 'St.02 Abwickler 1: Abwickelzeit überschritten', 62);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1131, 335, 1, 'St.02 Abwickler 1: Aufwickelzeit überschritten', 63);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1160, 335, 1, 'St.03 Roboter 1: nicht bereit', 64);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1161, 335, 1, 'St.03 Roboter 1: wird nicht fertig', 65);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1163, 335, 1, 'St.03 Roboter 1: Anrollzylinder geht nicht in Grundstellung', 66);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1164, 335, 1, 'St.03 Roboter 1: Anrollzylinder geht nicht in Arbeitsstellung', 67);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1165, 335, 1, 'St.03 Roboter 1: Zelle nicht angesaugt', 68);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1166, 335, 1, 'St.03 Roboter 1: Zelle verloren', 69);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1167, 335, 1, 'St.03 Roboter 1: Vakuum geht nicht weg', 70);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1169, 335, 1, 'St.03 Roboter 1: NIO-Ablage geht nicht runter', 71);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1170, 335, 1, 'St.03 Roboter 1: NIO-Ablage geht nicht hoch', 72);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1171, 335, 1, 'St.03 Roboter 1: Kamera nicht bereit', 73);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1172, 335, 1, 'St.03 Roboter 1: Kamera wird nicht fertig', 74);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1173, 335, 1, 'St.03 Roboter 1: Kamera meldet Fehler', 75);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1174, 335, 1, 'St.03 Roboter 1: Wandlungsfehler bei Kamera-Ergebnis', 76);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1175, 335, 1, 'St.03 Roboter 1: Messung Loch an Ecke nicht erkannt', 77);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1176, 335, 1, 'St.03 Roboter 1: Loch an Ecke nicht messbar', 78);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1177, 335, 1, 'St.03 Roboter 1: Messung Loch an Kante nicht erkannt', 79);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1178, 335, 1, 'St.03 Roboter 1: Loch an Kante nicht messbar', 80);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1179, 335, 1, 'St.03 Roboter 1: Zelle nicht messbar', 81);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1180, 335, 1, 'St.03 Roboter 1: Kalibrieren mit IO beendet', 82);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1181, 335, 1, 'St.03 Roboter 1: Kalibrieren mit NIO beendet', 83);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1192, 335, 1, 'St.04 Verbinder: Antrieb für Kante nicht bereit', 84);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1193, 335, 1, 'St.05 Verbinder: Antrieb für Kante meldet Fehler', 85);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1194, 335, 1, 'St.04 Verbinder: Lochwerkzeug geht nicht auf', 86);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1195, 335, 1, 'St.04 Verbinder: Lochwerkzeug geht nicht zu', 87);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1196, 335, 1, 'St.04 Verbinder: Stanzrestabsaugung nicht ok', 88);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1197, 335, 1, 'St.04 Verbinder: Undefinierter Verbindertyp', 89);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1198, 335, 1, 'St.04 Verbinder: Werkzeuggreifer geht nicht auf', 90);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1199, 335, 1, 'St.04 Verbinder: Werkzeuggreifer geht nicht zu', 91);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1200, 335, 1, 'St.04 Verbinder: Messer geht nicht auf ', 92);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1201, 335, 1, 'St.04 Verbinder: Messer geht nicht zu', 93);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1202, 335, 1, 'St.04 Verbinder: Trenngreifer geht nicht auf', 94);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1203, 335, 1, 'St.04 Verbinder: Trenngreifer geht nicht zu', 95);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1204, 335, 1, 'St.04 Verbinder: Trenngreifer geht nicht hoch', 96);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1205, 335, 1, 'St.04 Verbinder: Trenngreifer geht nicht runter', 97);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1206, 335, 1, 'St.04 Verbinder: Trenngreifer geht nicht zur Warteposition', 98);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1207, 335, 1, 'St.04 Verbinder: Trenngreifer geht nicht zum Verbinder', 99);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1208, 335, 1, 'St.04 Verbinder: Anrollgreifer geht nicht auf', 100);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1209, 335, 1, 'St.04 Verbinder: Anrollgreifer geht nicht zu', 101);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1210, 335, 1, 'St.04 Verbinder: Anrollgreifer geht nicht hoch', 102);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1211, 335, 1, 'St.04 Verbinder: Anrollgreifer geht nicht runter', 103);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1212, 335, 1, 'St.04 Verbinder: Anrollgreifer schwenkt nicht in Greifposition', 104);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1213, 335, 1, 'St.04 Verbinder: Anrollgreifer schwenkt nicht in Anrollposition', 105);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1214, 335, 1, 'St.04 Verbinder: Zustand Verbinder nicht definierbar (-->EZA)', 106);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1215, 335, 1, 'St.04 Verbinder: Anrollgreifer nicht sicher --> GSTF notwendig', 107);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1216, 335, 1, 'St.04 Verbinder: Vakuumsauger meldet Fehler, Verbinder verloren?', 108);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1217, 335, 1, 'St.04 Verbinder: Sollposition außerhalb des Fahrbereiches', 109);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1224, 335, 1, 'St.05 Zellenvereinzelung 2: Antrieb für Kante nicht bereit', 110);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1225, 335, 1, 'St.05 Zellenvereinzelung 2: Antrieb für Kante meldet Fehler', 111);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1226, 335, 1, 'St.05 Zellenvereinzelung 2: Antrieb für Band nicht bereit', 112);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1227, 335, 1, 'St.05 Zellenvereinzelung 2: Antrieb für Band meldet Fehler', 113);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1230, 335, 1, 'St.05 Zellenvereinzelung 2: Antrieb_Kante hinten nicht auf "stumpf"', 114);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1231, 335, 1, 'St.05 Zellenvereinzelung 2: Antrieb_Kante hinten nicht auf "scharf"', 115);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1232, 335, 1, 'St.05 Zellenvereinzelung 2: Antrieb_Kante vorn nicht auf "stumpf"', 116);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1233, 335, 1, 'St.05 Zellenvereinzelung 2: Antrieb_Kante vorn nicht auf "scharf"', 117);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1234, 335, 1, 'St.05 Zellenvereinzelung 2: keine Freigabe für Schlitten von den Dreheinheiten', 118);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1235, 335, 1, 'St.05 Zellenvereinzelung 1: keine Zelle erkannt', 119);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1257, 335, 1, 'St.05 Abwickler 2: Antrieb nicht bereit', 120);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1258, 335, 1, 'St.05 Abwickler 2: Antrieb meldet Fehler', 121);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1259, 335, 1, 'St.05 Abwickler 2: Abwicklezeit überschritten', 122);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1260, 335, 1, 'St.05 Abwickler 2: Aufwicklezeit überschritten', 123);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1288, 335, 1, 'St.06 Roboter 2: nicht bereit', 124);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1289, 335, 1, 'St.06 Roboter 2: wird nicht fertig', 125);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1291, 335, 1, 'St.06 Roboter 2: Anrollzylinder geht nicht in Grundstellung', 126);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1292, 335, 1, 'St.06 Roboter 2: Anrollzylinder geht nicht in Arbeitsstellung', 127);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1293, 335, 1, 'St.06 Roboter 2: Zelle nicht angesaugt', 128);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1294, 335, 1, 'St.06 Roboter 2: Zelle verloren', 129);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1295, 335, 1, 'St.06 Roboter 2: Vakuum geht nicht weg', 130);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1297, 335, 1, 'St.06 Roboter 2: NIO-Ablage geht nicht runter', 131);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1298, 335, 1, 'St.06 Roboter 2: NIO-Ablage geht nicht hoch', 132);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1299, 335, 1, 'St.06 Roboter 2: Kamera nicht bereit', 133);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1300, 335, 1, 'St.06 Roboter 2: Kamera wird nicht fertig', 134);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1301, 335, 1, 'St.06 Roboter 2: Kamera meldet Fehler', 135);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1302, 335, 1, 'St.06 Roboter 2: Wandlungsfehler bei Kamera-Ergebnis', 136);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1303, 335, 1, 'St.06 Roboter 2: Messung Loch an Ecke nicht erkannt', 137);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1304, 335, 1, 'St.06 Roboter 2: Loch an Ecke nicht messbar', 138);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1305, 335, 1, 'St.06 Roboter 2: Messung Loch an Kante nicht erkannt', 139);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1306, 335, 1, 'St.06 Roboter 2: Loch an Kante nicht messbar', 140);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1307, 335, 1, 'St.06 Roboter 2: Zelle nicht messbar', 141);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1308, 335, 1, 'St.06 Roboter 2: Kalibrieren mit IO beendet', 142);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1309, 335, 1, 'St.06 Roboter 2: Kalibrieren mit NIO beendet', 143);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1320, 335, 1, 'St.07 Etikettierer: nicht bereit', 144);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1321, 335, 1, 'St.07 Etikettierer: meldet Fehler', 145);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1322, 335, 1, 'St.07 Etikettierer: wird nicht fertig', 146);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1353, 335, 1, 'Robotercontroller: Robotercontroller nicht im AUTO-Mode', 147);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1354, 335, 1, 'Robotercontroller: Robotercontroller meldet Fehler', 148);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1355, 335, 1, 'Robotercontroller: Tasks werden nicht beendet', 149);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1356, 335, 1, 'Robotercontroller: Tasks werden nicht gestartet', 150);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1357, 335, 1, 'Robotercontroller: Schutztüren nicht geschlossen', 151);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1358, 335, 1, 'Robotercontroller: Not-Aus ausgelöst', 152);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1359, 335, 1, 'Robotercontroller: Tasks werden nicht fortgesetzt', 153);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (1360, 335, 1, 'Robotercontroller: zum Start des Robotercontrollers Türen schliessen !', 154);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (2000, 335, 1, 'alle Meldungen siehe Zappa 1 von 2000 bis 2360', 155);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (3000, 335, 1, 'alle Meldungen siehe Zappa 1 von 3000 bis 3360', 156);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (4000, 335, 1, 'alle Meldungen siehe Zappa 1 von 4000 bis 4360', 157);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5000, 335, 1, 'St00 Türen verriegeln nicht (E1.4->1)', 158);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5001, 335, 1, 'St00 Türen entriegeln nicht (E1.4->0)', 159);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5002, 335, 1, 'St00 Notaus wegen Über- oder Unterdruck am Hauptluftventil (E1.0->1)', 160);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5003, 335, 1, 'St00 Alles zurückgesetzt, Maschine ausräumen.', 161);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5004, 335, 1, 'St00 Notaus weil verriegelte Türen geöffnet wurden (E1.3->1)', 162);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5005, 335, 1, 'St00 Profibus-Teilnehmer ausgefallen, siehe Diagnose-Seite.', 163);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5064, 335, 1, 'St.01 Tisch: Antrieb Time-Out', 164);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5065, 335, 1, 'St.01 Tisch: Antrieb meldet Fehler', 165);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5066, 335, 1, 'St.01 Schott nicht geschlossen (E64.0->1. E64.1->0)', 166);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5067, 335, 1, 'St.01 Schott nicht offen (E64.0->0. E64.1->1)', 167);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5068, 335, 1, 'St.01 Kamera wird nicht fertig', 168);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5069, 335, 1, 'St.01 St. 2 und 3 werden nicht fertig', 169);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5070, 335, 1, 'St.01 Multicodereader meldet Fehler', 170);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5071, 335, 1, 'St.01 Multicodereader Time-Out', 171);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5072, 335, 1, 'St.01 Multicodereader findet keinen Code', 172);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5073, 335, 1, 'St.01 Datenübergabe ans Transfer: keine Bereitschaft', 173);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5074, 335, 1, 'St.01 Datenübergabe ans Transfer: wird nicht fertig', 174);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5075, 335, 1, 'St.01 Datenübergabe ans Transfer: keine Quittierung', 175);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5076, 335, 1, 'St.01 Übergabe ans Transfer: Anforderung 2 fehlt', 176);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5077, 335, 1, 'St.01 Übergabe ans Transfer: Anforderung 3 fehlt', 177);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5078, 335, 1, 'St.01 Übergabe ans Transfer: Anforderung 4 fehlt', 178);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5096, 335, 1, 'St.01 Kamera: Ethernet-Verbindung kann nicht hergestellt werden', 179);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5097, 335, 1, 'St.01 Kamera: Umschaltung der Scene nicht gestartet', 180);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5098, 335, 1, 'St.01 Kamera: Kameraprüfung nicht gestartet', 181);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5099, 335, 1, 'St.01 Kamera: Kamera antwortet nicht', 182);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5100, 335, 1, 'St.01 Kamera: zu kurzes Antwort-Telegramm', 183);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5101, 335, 1, 'St.01 Kamera: Konvertierungsfehler', 184);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5102, 335, 1, 'St.01 Kamera: Löcher nicht gefunden', 185);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5128, 335, 1, 'St.02 X-Achse Time-Out', 186);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5129, 335, 1, 'St.02 X-Achse meldet Fehler (siehe EZA-Diagnose-Bild)', 187);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5130, 335, 1, 'St.02 Y-Achse Time-Out', 188);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5131, 335, 1, 'St.02 Y-Achse meldet Fehler (siehe EZA-Diagnose-Bild)', 189);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5132, 335, 1, 'St.02 Reinigungseinheit nicht oben (E66.0->1, E66.1->0)', 190);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5133, 335, 1, 'St.02 Reinigungseinheit nicht unten (E66.0->0, E66.1->1)', 191);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5134, 335, 1, 'St.02 Dispensgerät nicht bereit (E66.4->1)', 192);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5135, 335, 1, 'St.02 Dispensgerät wird nicht fertig (E66.5->1)', 193);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5136, 335, 1, 'St.02 Dispensgerät: Temperatur nicht ok (E66.6->1)', 194);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5137, 335, 1, 'St.02 Dispensgerät meldet Fehler (E66.7->0)', 195);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5138, 335, 1, 'St.02 Dispensgerät startet nicht (E66.4->0)', 196);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5139, 335, 1, 'St.02 Kamera wird nicht fertig', 197);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5140, 335, 1, 'St.02 Fehler in der Zellendefinition', 198);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5141, 335, 1, 'St.02 Reinigungspapier wechseln', 199);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5160, 335, 1, 'St.02/03 Kamera nicht bereit (E70.0->1, E70.1->0, E70.2->0, E70.4->1)', 200);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5161, 335, 1, 'St.02/03 Kamera startet nicht (E70.0->1, E70.2->1, E70.4->0)', 201);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5162, 335, 1, 'St.02/03 Kamera wird nicht fertig (E70.1->1)', 202);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5163, 335, 1, 'St.02/03 Kamera meldet Fehler (E70.3->0)', 203);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5192, 335, 1, 'St.03 X-Achse Time-Out', 204);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5193, 335, 1, 'St.03 X-Achse meldet Fehler (siehe EZA-Diagnose-Bild)', 205);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5194, 335, 1, 'St.03 Y-Achse Time-Out', 206);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5195, 335, 1, 'St.03 Y-Achse meldet Fehler (siehe EZA-Diagnose-Bild)', 207);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5196, 335, 1, 'St.03 Reinigungseinheit nicht oben (E68.0->1, E68.1->0)', 208);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5197, 335, 1, 'St.03 Reinigungseinheit nicht unten (E68.0->0, E68.1->1)', 209);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5198, 335, 1, 'St.03 Dispensgerät nicht bereit (E68.4->1)', 210);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5199, 335, 1, 'St.03 Dispensgerät wird nicht fertig (E68.5->1)', 211);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5200, 335, 1, 'St.03 Dispensgerät: Temperatur nicht ok (E68.6->1)', 212);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5201, 335, 1, 'St.03 Dispensgerät meldet Fehler (E68.7->0)', 213);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5202, 335, 1, 'St.03 Dispensgerät startet nicht (E68.4->0)', 214);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5203, 335, 1, 'St.03 Kamera wird nicht fertig', 215);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5204, 335, 1, 'St.03 Fehler in der Zellendefinition', 216);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (5205, 335, 1, 'St.03 Reinigungspapier wechseln', 217);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (6000, 335, 1, 'alle Meldungen siehe Kappa 1 von 6000 bis 6205', 218);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (7000, 335, 1, '...', 219);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8000, 335, 1, 'St00 Türen verriegeln nicht (E1.4->1)', 220);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8001, 335, 1, 'St00 Türen entriegeln nicht (E1.4->0)', 221);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8002, 335, 1, 'St00 Notaus wegen Über- oder Unterdruck am Hauptluftventil (E1.0->1)', 222);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8003, 335, 1, 'St00 Alles zurückgesetzt, Maschine ausräumen.', 223);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8004, 335, 1, 'St00 Notaus weil verriegelte Türen geöffnet wurden (E1.3->1)', 224);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8005, 335, 1, 'St00 Profibus-Teilnehmer ausgefallen, siehe Diagnose-Seite.', 225);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8064, 335, 1, 'St.01 Tisch: Timeout Tisch', 226);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8065, 335, 1, 'St.01 Tisch: Sensorfehler E63.2/E63.3', 227);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8066, 335, 1, 'St.01 Tisch: Sensorfehler E63.0/E63.1', 228);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8160, 335, 1, 'St.03 Vlieszuführung: Vlies Ende/Abriss während Transport', 229);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8161, 335, 1, 'St.03 Vlieszuführung: Timeout Transport', 230);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8162, 335, 1, 'St.03 Vlieszuführung: Fehler/Timeout Anlagekante', 231);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8163, 335, 1, 'St.03 Vlieszuführung: Fehler/Timeout Andruckrollen', 232);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8164, 335, 1, 'St.03 Vlieszuführung: Fehler/Timeout Kantensteuerung', 233);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8165, 335, 1, 'St.03 Vlieszuführung: Fehler Transportantrieb nicht bereit', 234);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8166, 335, 1, 'St.03 Vlieszuführung: Verkleidung offen', 235);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (8168, 335, 1, 'St.03 Vlieszuführung: Rollenende erkannt', 236);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (9000, 335, 1, 'nocht nicht vorhanden', 237);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10000, 335, 1, 'St00 Türen verriegeln nicht (E4.0->1, E4.4->1)', 238);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10001, 335, 1, 'St00 Türen entriegeln nicht (E4.0->0, E4.4->0)', 239);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10002, 335, 1, 'St00 Notaus wegen Über- oder Unterdruck am Hauptluftventil (E1.0->1)', 240);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10003, 335, 1, 'St00 Alles zurückgesetzt, Maschine ausräumen.', 241);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10004, 335, 1, 'St00 Notaus weil verriegelte Türen geöffnet wurden (E1.3->1)', 242);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10005, 335, 1, 'St00 Profibus-Teilnehmer ausgefallen, siehe Diagnose-Seite.', 243);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10006, 335, 1, 'St00 Notaus wegen Kollisionegefahr beim Verfahren', 244);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10008, 335, 1, 'St00 Fehler im Linkbus links', 245);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10009, 335, 1, 'St00 Fehler im Linkbus rechts', 246);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10010, 335, 1, 'St00 Lifebit auf dem Linkbus fehlt', 247);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10011, 335, 1, 'St00 Transfertür hinten bitte schließen und quittieren', 248);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10012, 335, 1, 'St00 Transfertür vorn bitte schließen und quittieren', 249);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10016, 335, 1, 'eSM: ESTOP aktiv', 250);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10017, 335, 1, 'eSM: Guard nicht aktiv', 251);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10018, 335, 1, 'eSM: Endstufe wird kurz abgeschaltet', 252);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10019, 335, 1, 'eSM: Starten schlug fehl. Bitte Endstufe, Verkabelung und Motor überprüfen.', 253);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10020, 335, 1, 'eSM: kein Stationswiederkehr nach dem ausschalten. Bitte Profibus überprüfen.', 254);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10032, 335, 1, 'Hauptachse: kein Fehlerreset der Achse', 255);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10033, 335, 1, 'Hauptachse: Achse initialisiert nicht', 256);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10034, 335, 1, 'Hauptachse: Achse nicht enabled', 257);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10035, 335, 1, 'Hauptachse: Achse nicht busy (fährt nicht)', 258);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10036, 335, 1, 'Hauptachse: Achse nicht bereit', 259);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10037, 335, 1, 'Hauptachse: Achse referenziert nicht', 260);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10053, 335, 1, 'Transfer referenziert nicht vor Modul', 261);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10064, 335, 1, 'Übergabe: Zelle ist nicht mehr bereit', 262);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10065, 335, 1, 'Übergabe: Zelle ist nicht mehr fertig', 263);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10066, 335, 1, 'Übergabe: Vliesbahn ist zu kurz', 264);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10072, 335, 1, 'Modul öffnet Schott nicht', 265);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10073, 335, 1, 'Modul fährt Vakuumtisch nicht aus', 266);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10074, 335, 1, 'Modul öffnet Bänder nicht', 267);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10075, 335, 1, 'Modul öffnet Kralle nicht', 268);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10076, 335, 1, 'Modul schließt Klemmung nicht', 269);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10077, 335, 1, 'Modul fährt Vakuumtisch nicht ein', 270);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10078, 335, 1, 'Modul fährt Vließ nicht ein', 271);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10079, 335, 1, 'Modul zieht Vließ nicht ein', 272);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10080, 335, 1, 'Antrieb 11: kein Fehlerreset der Achse', 273);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10081, 335, 1, 'Antrieb 12: kein Fehlerreset der Achse', 274);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10082, 335, 1, 'Antrieb 21: kein Fehlerreset der Achse', 275);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10083, 335, 1, 'Antrieb 22: kein Fehlerreset der Achse', 276);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10084, 335, 1, 'Antrieb 11: Achse initialisiert nicht', 277);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10085, 335, 1, 'Antrieb 12: Achse initialisiert nicht', 278);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10086, 335, 1, 'Antrieb 21: Achse initialisiert nicht', 279);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10087, 335, 1, 'Antrieb 22: Achse initialisiert nicht', 280);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10088, 335, 1, 'Antrieb 11: Achse nicht enabled', 281);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10089, 335, 1, 'Antrieb 12: Achse nicht enabled', 282);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10090, 335, 1, 'Antrieb 21: Achse nicht enabled', 283);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10091, 335, 1, 'Antrieb 22: Achse nicht enabled', 284);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10092, 335, 1, 'Antrieb 11: Achse nicht busy (fährt nicht)', 285);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10093, 335, 1, 'Antrieb 12: Achse nicht busy (fährt nicht)', 286);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10094, 335, 1, 'Antrieb 21: Achse nicht busy (fährt nicht)', 287);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10095, 335, 1, 'Antrieb 22: Achse nicht busy (fährt nicht)', 288);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10096, 335, 1, 'Antrieb 11: Achse nicht bereit', 289);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10097, 335, 1, 'Antrieb 12: Achse nicht bereit', 290);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10098, 335, 1, 'Antrieb 21: Achse nicht bereit', 291);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10099, 335, 1, 'Antrieb 22: Achse nicht bereit', 292);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10100, 335, 1, 'Antrieb 11: Achse referenziert nicht', 293);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10101, 335, 1, 'Antrieb 12: Achse referenziert nicht', 294);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10102, 335, 1, 'Antrieb 21: Achse referenziert nicht', 295);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10103, 335, 1, 'Antrieb 22: Achse referenziert nicht', 296);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10104, 335, 1, 'Antrieb 12: Achse nicht im Gear-Mode', 297);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10105, 335, 1, 'Antrieb 22: Achse nicht im Gear-Mode', 298);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10112, 335, 1, 'Zahnriementransport am Wagen 1 nicht geöffent', 299);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10113, 335, 1, 'Zahnriementransport am Wagen 2 nicht geöffnet', 300);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10114, 335, 1, 'Zahnriementransport am Wagen 1 nicht geschlossen', 301);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10115, 335, 1, 'Zahnriementransport am Wagen 2 nicht geschlossen', 302);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10116, 335, 1, 'Auflageblech 1 von Wagen 1 nicht ausgefahren', 303);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10117, 335, 1, 'Auflageblech 2 von Wagen 1 nicht ausgefahren', 304);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10118, 335, 1, 'Auflageblech 1 von Wagen 2 nicht ausgefahren', 305);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10119, 335, 1, 'Auflageblech 2 von Wagen 2 nicht ausgefahren', 306);
INSERT INTO T_ALARM_DEF (alid, treiber_id, alarm_class, alarm_desc, seq_nr) VALUES (10120, 335, 1, 'Fehler bei Vliesübergabe Transfer -> Modul: zulässiger Fahrweg überschritten', 307);
